---
output:
  html_document: default
  word_document: default
  pdf_document: default
---
```{r message=F, include=F}
  load(file="variables.RData")
  
  library(psych)
  library(tidyverse)
  library(tools)
  library(knitr)
  library(scales)
```

---
title: "Arteriovenous fistula in the head and neck region - systematic review of cases"
author:
- name: Jurriën L.A. Embrechts
  affiliation: Leids Universitair Medisch Centrum
- name: Rilke Snoeren
  affiliation: Vrije Universiteit Medisch Centrum
- name: Johannes C.F. Ket
  affiliation: Vrije Universiteit Medisch Centrum
- name: Prof Remco B.R. de Bree
  affiliation: Utrecht Cancer Centre
date: 
bibliography: complete.bib
csl: build/nature.csl

---

# Arteriovenous fistula in the head and neck region - systematic review of cases

## Abstract
Object:
Methods:
Results:
Conclusions:

## Background and Significance
An arteriovenous fistula (AVF) is a type of vascular malformation that consists of a direct connection between an artery and a vein without a intervening capillary bed or nidus. These rare entities are distinguished into two main groups in literature, primary (congenital or spontaneous) and secondary (incidental trauma or iatrogenic). 
Due to the rarity of this lesion no large trials about their treatment method nor etiology exist to our knowledge. 
We compare these two groups to identify differences in demographics, clinical presentation and follow-up and we try to identify risk factors that contribute to their existence.

## Relevance
Literature regarding extracranial AVFs in the head and neck is rare. The most recent literature overview considering vascular anomalies in general in the head and neck is performed in 2010[@Buckmiller:2010hn]. To our best knowledge no descriptive study of pooled data from published papers regarding extracranial AVFs in the head and neck is yet performed. Little is known about characteristics of extracranial AVFs in the head and neck. This study will analyze all reported literature and perform a meta-analysis in order to define clinical characteristics of extracranial AVFs in the head and neck. Additionally, no comparative study between congenital and non-congenital AVFs is published. We investigate possible differences between congenital and non-congenital AVFs other than the genesis. Should they be seen as two different vascular anomalies? 

## Introduction
Vascular anomalies consist of a broad, heterogeneous, spectrum of vascular tumors and vascular malformations. The major difference to distinguish between vascular tumors and malformations is the presence of increased endothelial turnover on histopathology in vascular tumors.[@Lowe:2012gd] Both tumors and malformed vascular tissues can be fast- or slow-flow lesions. Slow-flow lesions consist of capillaries, lymphatic vessels, veins or a combination. Fast-flow lesions include all with the presence of arterial flow and are potentially more aggressive.[@Behr:2013gg; @Wassef:2015dy] Fast-flow vascular malformations are divided in arteriovenous malformations (AVMs) and arteriovenous fistulas (AVFs).
The term cirsoid aneurysm was applied to vascular malformations of the scalp in 1833 by Brecht  and is used to describe a fistulous connection between the arterial feeding vessels of the scalp and the draining veins without an intervening capillary bed.[@ELKIN:1924hw; @Gurkanlar:2006it]

Ultrasound, CT, and angiography are commonly used to detect the AVF where four-dimensional CT angiography (4D- CTA) can be used to better visualize the blood flow within the AVF.[@Fujimura:2013hda] 
Differentiation between AVFs and AVMs can be challenging. AVFs are a direct connection between an artery and a vein with no communicating capillaries, yet multiple communicating sites in a single AVF is possible. Equally in AVMs a capillary bed is bypassed by direct artery to vein connections. Commonly in AVMs a central nidus, the center of an AVM whence tortuous collaterals are formed, is present [@Nassiri:2015wb]. Blood pressure in this efferent vein is higher than normal which leads to dilated, more rigid veins. AVMs are congenital due to errors in the embryonic or fetal vascular differentiation [@Lowe:2012gd, @Wassef:2015dy]. AVFs are frequently a result of traumatic vascular injury or iatrogenic after surgery, yet congenital AVFs are also known [@Nassiri:2015wb]. Genes which are recognized within vascular malformation syndromes with AVMs are also found in these syndromes and AVFs [@Wassef:2015dy]. Conventional work-up to determine the nature of a suspected vascular anomaly consists of imaging. This work-up can be done using ultrasound, CTA, MRA, and/or angiography. The gold standard is conventional angiography. In absence of a central nidus, for which no histological markers are known, determination between small AVMs and (congenital) AVFs can remain difficult.   
This review focuses on extracranial AVFs in the head and neck. The head and neck region is highly vascularized and contains multiple important nerves. Treatment can be challenging due to airway compromise, risk of bleeding and neural damage and requires a multidisciplinary team. 
Since intracranial AVFs require a different approach and treatment and produce different symptoms they will not be included in this study.  Embolic treatment is the treatment of choice in cerebral AVFs, no consensus is made regarding first choice therapy for extracranial AVFs {Tsai:2016bq}.Lastly surgical approach to intracranial vascular anomalies is not comparable with surgery on extracranial AVFs.  
Exact incidence of extracranial AVFs in the head and neck is unknown, but current availability of literature is illustrative of its rarity. AVFs in the head and neck can cause disfigurement, distal ischemia, pain and pulsatile tinnitus. No randomized trials have been performed yet to investigate the best treatment and timing, no consensus is made regarding therapy. Reported treatment options include medication, surgery and endovascular interventions using different agents for embolization: alcohol, onyx, glue and coils {Buckmiller:2010hn, Kim:2003di}.
Objectives and study design 
With this systematic review we aim to investigate clinical characteristics, natural course and course before and after treatment of AVFs in the head and neck region. Investigated clinical characteristics consists of patient characteristics (age, gender, ancestry), number of fistulas, location: afferent and efferent vein(s), size of AVF, genesis of AVF (after surgery, trauma of congenital/spontaneously), duration between trauma (if present) and presentation. Also used diagnostics, symptoms after treatment, adverse events, recurrence and time to follow up will be noted. 
All papers on extracranial AVFs in the head and neck region will be studied including cirsoid aneurysms, AVFs of the scalp which occur both as congenital and after (penetrating) trauma of the scalp [@Gurkanlar:2006it]. We aim to investigate if there is a difference in symptoms, location, course and prognosis between congenital/spontaneous and traumatic/iatrogenic AVFs. Additionally, comparison between congenital and non-congenital AVFs will be performed regarding timing of treatment. Should they be seen as two independent vascular malformations? 
Secondary the aim is to find out if AVFs most often originate after trauma, surgery or spontaneously, what the average time of presentation is after a trauma (or surgery) and what treatment modality is used. Lastly we want to provide an overview of current literature and a fundament for future research and add two cases to the current literature.

## Objectives and study design
With this systematic review we aim to investigate clinical characteristics, natural course and course before and after treatment of AVFs in the head and neck region. Investigated clinical characteristics consists of patient characteristics (age, gender, ancestry), number of fistulas, location: afferent and efferent vein(s), size of AVF, genesis of AVF (after surgery, trauma of congenital/spontaneously), duration between trauma (if present) and presentation. Also used diagnostics, symptoms after treatment, adverse events, recurrence and time to follow up will be noted. 
All papers on extracranial AVFs in the head and neck region will be studied including cirsoid aneurysms, AVFs of the scalp which occur both as congenital and after (penetrating) trauma of the scalp (8). We aim to investigate if there is a difference in symptoms, location, course and prognosis between congenital/spontaneous and traumatic/iatrogenic AVFs. Additionally, comparison between congenital and non-congenital AVFs will be performed regarding timing of treatment. Should they be seen as two independent vascular malformations? 
Secondary the aim is to find out if AVFs most often originate after trauma, surgery or spontaneously, what the average time of presentation is after a trauma (or surgery) and what treatment modality is used. Lastly we want to provide an overview of current literature and a fundament for future research and add two cases to the current literature.


## Methods
### Study selection
We performed a systematic search on PUBMED, EMBASE and the Cochrane library using definitions for AVFs and the head and neck region (appendix 1[//]( Methode van Hans Ket komt hier en in ‘supplementary information)). Only studies from January 2005 through May 2016 were included. Titles and abstracts where screened on potential relevant studies by two independent researchers using the following inclusion criteria: extracranial AVFs in head and/or neck, spinal extradural AVF, cirsoid aneurysm, AVF is confirmed by imaging or histopathology restricted to only human subjects. When no agreement was reached on paper inclusion the last author was consulted. Subsequently the full text was examined for final inclusion. When no full text was available, the AVF was purposely surgically constructed, no individual patient data was available or the AVF was not located extracranial and extradural and in the head and neck region; the study, case or case series was excluded. Also two unpublished additional cases were added to the database. 

### Data extraction
Individualized patient data was collected from the included papers. This extracted data is pooled and analyzed. Important parameters include patient characteristics (age, gender) and genesis of the AVF. Genesis is divided in a primary and secondary origin. Primary includes spontaneous or congenital genesis of the AVF, secondary genesis include AVFs after surgery or trauma. Other parameters that are subtracted from included papers are fistula characteristics: afferent arterial feeders and efferent venous drainage, symptoms at presentation, time between presentation and surgery or trauma and treatment modality. Additionally, used diagnostics, follow up time and recurrence are tracked. 

### Data analysis
Data from included papers is pooled and analysed with r R.version$version.string and Rstudio Version r RStudio.Version()$version RStudio, Inc. using the tidyverse 1.2.1, psych 1.7.3.2.1 and readxl 1.0.0 package. Primary AVFs are compared with secondary AVFs on baseline characteristics as gender and age at presentation. Also afferent arterial feeders, efferent venous drainage, treatment modality, symptoms and number of fistulas are compared. 
Data of primary and secondary AVFs are compared using independent two-sided t-test for normal distributed continuous variables, Mann Whitney U test for not normally distributed continuous variables and fisher exact tests for comparison of categorical variables. Statistical significance is defined at a p value <0.05. Analysis is performed on all available data from included individual patient information. 

## Results
Our systematic search yielded a total of 3247 articles in the time frame from January 2005 through May 2016. Selection on title and abstract eliminated 2925 articles after consensus was reached between the reviewers. The residual 322 articles where perused and 207 where included, which comprised 300 patients in total. 

### Demographics
Table 1 summarizes number of patients, age, sex and follow-up included `r nrow(AVF)` patients. Age was not normally distributed (shapiro wilk p-value < 0.01) with a mean of `r round((describe(AVF$Age)$mean), 1)` years (standard deviation `r round((describe(AVF$Age)$sd), 1)` years, oldest patient is `r describe(AVF$Age)$max` years old, youngest a few days), `r percent(nrow(AVF %>% filter(Gender == "m"))/nrow(AVF))` was male, `r percent(nrow(primair_AVF)/nrow(AVF))` had a primary genesis, `r percent(nrow(secundair_AVF)/nrow(AVF))` a secondary genesis and `r nrow(AVF) - nrow(primair_AVF) - nrow(secundair_AVF)` casus (`r percent((nrow(AVF)-nrow(primair_AVF)-nrow(secundair_AVF))/nrow(AVF))`) did not report the genesis.

**Table 1: Demographics of the population**
`r kable(results_demographics)`
		
### Clinical presentation
Overall patients presented 3.6 years (`r round(describe(AVF$TimeSinceFirstSymptoms)$mean,1)` months) after the onset of the first symptoms.
In `r nrow(filter(AVF, is.na(Symptoms)))` cases (`r percent(nrow(filter(AVF, is.na(Symptoms)))/nrow(AVF))`) no symptoms at presentation are disclosed. Of the remaining `r nrow(AVF)-nrow(filter(AVF, is.na(Symptoms)))` patients `r nrow(filter(AVF, grepl("PULM", Symptoms)))` (`r percent(nrow(filter(AVF, grepl("PULM", Symptoms)))/nrow(AVF))`) presented with a pulsatile mass.  Tinnitus, pulsatile tinnitus or murmur is reported in `r nrow(filter(AVF, grepl("TIN|MUR|PTIN", Symptoms)))` (`r percent(nrow(filter(AVF, grepl("TIN|MUR|PTIN", Symptoms)))/nrow(AVF))`) patients with a objective bruit or thrill in `r nrow(filter(AVF, grepl("TR|BR", Symptoms)))` (`r percent(nrow(filter(AVF, grepl("TR|BR", Symptoms)))/nrow(AVF))`) of total patients. Headache was present in `r nrow(filter(AVF, grepl("HEAD", Symptoms)))` (`r percent(nrow(filter(AVF, grepl("HEAD", Symptoms)))/nrow(AVF))`) and was significantly more common in patients with a primary genesis than patients with a secondary origin of the AVF *(p < 0.01)*. `r nrow(filter(AVF, grepl("ALC|ATAX|DYSA|INTB|INES|INST", Symptoms)))` (`r percent(nrow(filter(AVF, grepl("ALC|ATAX|DYSA|INTB|INES|INST", Symptoms)))/nrow(AVF))`) patients presented with symptoms of intracranial pathology[^2] [\\](nog wat aanpassen deze definitie.), `r nrow(filter(AVF, grepl("INCO|MYE|NEDE|QUA|RADI|SPCC|ULE|UAI|UAMW", Symptoms)))` (`r percent(nrow(filter(AVF, grepl("INCO|MYE|NEDE|QUA|RADI|SPCC|ULE|UAI|UAMW", Symptoms)))/nrow(AVF))`) patients with signs of spinal cord compression[^3], `r nrow(filter(AVF, grepl("BLV|DECV|DIP|VFD", Symptoms)))` (`r percent(nrow(filter(AVF, grepl("BLV|DECV|DIP|VFD", Symptoms)))/nrow(AVF))`) patients with visual impairment[^1], `r nrow(filter(AVF, grepl("BLEED|BLEEDT|ECCY|GUMB|HEMO", Symptoms)))` (`r percent(nrow(filter(AVF, grepl("BLEED|BLEEDT|ECCY|GUMB|HEMO", Symptoms)))/nrow(AVF))`) patients with signs of extracranial hemorrhage[^4] and `r nrow(filter(AVF, grepl("CHEM|EPIP|HIP|ORBS|PROP", Symptoms)))` (`r percent(nrow(filter(AVF, grepl("CHEM|EPIP|HIP|ORBS|PROP", Symptoms)))/nrow(AVF))`) patients with ocular symptoms[^5].
  
The secondary group consists of `r nrow(secundair_AVF)` patients: `r nrow(filter(AVF, grepl("^T", Genesis)))` (`r percent(nrow(filter(AVF, grepl("^T", Genesis)))/nrow(secundair_AVF))`) patients had a trauma (blunt or penetrating trauma) as a history, `r nrow(filter(AVF, grepl("^OK", Genesis)))` (`r percent(nrow(filter(AVF, grepl("^OK", Genesis)))/nrow(secundair_AVF))`) patients had invasive treatment and `r nrow(filter(AVF, grepl("^SM", Genesis)))` patient developed an AVF secondary to invasive squamous cell carcinoma of the oropharynx. `r nrow(filter(AVF, grepl("^OKCVC", Genesis)))` (`r percent(nrow(filter(AVF, grepl("^OKCVC", Genesis)))/nrow(filter(AVF, grepl("^OK", Genesis))))`) patients of the invasive treatment group developed hAVFs [//](nog geen definitie aanwezig) after insertion of a central venous catheter in the internal jugular vein. `r nrow(filter(AVF, grepl("^OKHT", Genesis)))` (`r percent(nrow(filter(AVF, grepl("^OKHT", Genesis)))/nrow(secundair_AVF))`) patients developed an AVF after hair transplantation surgery and `r nrow(filter(AVF, grepl("^OKICD|OKPLR", Genesis)))` (`r percent(nrow(filter(AVF, grepl("^OKICD|OKPLR", Genesis)))/nrow(secundair_AVF))`) patients  developed a hAVF after pacemaker or icd lead removal.[//](nog geen definitie aanwezig)

**Table 2: Clinical presentation of the population**
`r kable(results_clinicalPresentation)`

### Anatomical distribution
The vertebral artery (`r percent(nrow(filter(AVF, grepl("VA", Aff)))/nrow(AVF))`), thyroid artery (`r percent(nrow(filter(AVF, grepl("TA", Aff)))/nrow(AVF))`) and superficial temporal artery (`r percent(nrow(filter(AVF, grepl("STA", Aff)))/nrow(AVF))`) were the most common affected afferent vessels. The jugular vein (`r percent(nrow(filter(AVF, grepl("JV", Eff)))/nrow(AVF))`) and the internal jugular vein (`r percent(nrow(filter(AVF, grepl("IJV", Eff)))/nrow(AVF))`) were the most common affected efferent vessels. 

There was a significantly *(p<0.05)* greater occurence of a fistula in the group of primary genesis than in the group of secondary genesis in the following vessels: palatine artery (`r percent(nrow(filter(primair_AVF, grepl("PA", Aff)))/nrow(primair_AVF))` vs `r percent(nrow(filter(secundair_AVF, grepl("PA", Aff)))/nrow(secundair_AVF))`), epidural venous plexus (`r percent(nrow(filter(primair_AVF, grepl("EVP", Eff)))/nrow(primair_AVF))` vs `r percent(nrow(filter(secundair_AVF, grepl("EVP", Eff)))/nrow(secundair_AVF))`), posterior auricular artery (`r percent(nrow(filter(primair_AVF, grepl("PAA", Aff)))/nrow(primair_AVF))` vs `r percent(nrow(filter(secundair_AVF, grepl("PAA", Aff)))/nrow(secundair_AVF))`), external jugular vein (`r percent(nrow(filter(primair_AVF, grepl("EJV", Eff)))/nrow(primair_AVF))` vs `r percent(nrow(filter(secundair_AVF, grepl("EJV", Eff)))/nrow(secundair_AVF))`), aortic arch (`r percent(nrow(filter(primair_AVF, grepl("AA", Aff)))/nrow(primair_AVF))` vs `r percent(nrow(filter(secundair_AVF, grepl("AA", Aff)))/nrow(secundair_AVF))`), epidural veins (`r percent(nrow(filter(primair_AVF, grepl("EV", Eff)))/nrow(primair_AVF))` vs `r percent(nrow(filter(secundair_AVF, grepl("EV", Eff)))/nrow(secundair_AVF))`), occipital artery (`r percent(nrow(filter(primair_AVF, grepl("OA", Aff)))/nrow(primair_AVF))` vs `r percent(nrow(filter(secundair_AVF, grepl("OA", Aff)))/nrow(secundair_AVF))`), ophthalmic vein (`r percent(nrow(filter(primair_AVF, grepl("OV", Eff)))/nrow(primair_AVF))` vs `r percent(nrow(filter(secundair_AVF, grepl("OV", Eff)))/nrow(secundair_AVF))`) and cervical epidural venous plexus (`r percent(nrow(filter(primair_AVF, grepl("CEVP", Eff)))/nrow(primair_AVF))` vs `r percent(nrow(filter(secundair_AVF, grepl("CEVP", Eff)))/nrow(secundair_AVF))`).[\\](Mogelijk alle epidurale plexus nog samenvoegen?)
There was a significantly *(p<0.05)* greater occurence of a fistula in the group of secondary genesis than in the group of primary genesis in the following vessels: common carotid artery (`r percent(nrow(filter(secundair_AVF, grepl("CCA", Aff)))/nrow(secundair_AVF))` vs `r percent(nrow(filter(primair_AVF, grepl("CCA", Aff)))/nrow(primair_AVF))`), internal jugular vein (`r percent(nrow(filter(secundair_AVF, grepl("IJV", Eff)))/nrow(secundair_AVF))` vs `r percent(nrow(filter(primair_AVF, grepl("IJV", Eff)))/nrow(primair_AVF))`), subclavian artery (`r percent(nrow(filter(secundair_AVF, grepl("SA", Aff)))/nrow(secundair_AVF))` vs `r percent(nrow(filter(primair_AVF, grepl("SA", Aff)))/nrow(primair_AVF))`), subclavian vein (`r percent(nrow(filter(secundair_AVF, grepl("SV", Eff)))/nrow(secundair_AVF))` vs `r percent(nrow(filter(primair_AVF, grepl("SV", Eff)))/nrow(primair_AVF))`) and the jugular vein (`r percent(nrow(filter(secundair_AVF, grepl("JV", Eff)))/nrow(secundair_AVF))` vs `r percent(nrow(filter(primair_AVF, grepl("JV", Eff)))/nrow(primair_AVF))`). 

`r percent(nrow(filter(secundair_AVF, grepl("IJV", Eff)) %>% filter(grepl("OKCVC", Genesis)))/nrow(filter(secundair_AVF, grepl("IJV", Eff))))` of fistula comprising the internal jugular vein and `r percent(nrow(filter(secundair_AVF, grepl("BCV|SV", Eff)) %>% filter(grepl("OKCVC", Genesis)))/nrow(filter(secundair_AVF, grepl("BCV|SV", Eff))))` comprising the brachiocephalic or subclavian veins where due to intravenous catheter placement. 

**Table 3: Anatomical distribution of AVF in the head and neck**
`r kable(results_afferent)`
`r kable(results_efferent)`

### Treatment
`r percent(nrow(pure_endovascular)/nrow(AVF))` received endovascular treatment, `r percent(nrow(pure_surgical)/nrow(AVF))` surgical and `r nrow(both)` patients (`r percent(nrow(both)/nrow(AVF))`) received a combination of surgical and endovascular treatment. `r nrow(refused_AVF)` people refused treatment for their AVF. `r nrow(symptomsAfterTreatment)` people had residual symptoms after treatment, `r nrow(adverseEvents)` people had an adverse event during or after their therapy of whom `r nrow(adverseEventsDeath)` people died. The causes of death were comprised of two cases of pulmonary embolism, septic shock and cerebral hyperperfusion syndrome. [//](Je zou het liefst ook statistiek van treatment naar outcome willen weten maar de outcome is hierin toch erg lastig te meten)

In table 4 we distinguish surgical therapy (ligation or excision), embolization with different agents (liquid, sclerosing, particulate or mechanical), multipile embolization, combined therapy (surgical and embolization) and direct puncture.

**Table 4: Treatment outcomes**
`r kable(results_treatment)`

## Conclusion

### Demographics
- Number of patients secondary hAVF twice the number of primary
- Most patients presented in their thirties allthough the age of presentation was significantly higher in secondary AVFs
- There was no sex predilection in both groups

### Clinical presentation
- Symptoms existed multiple years before presentation, in the primary group the standard deviation of presentation was much higher than in the secondary group.
- We saw a significantly higher amount of ocular symptoms and headache in the primary group. 
- In secondary AVF objectivation of sound was more common than in primary AVF (more superficial localisation of the lesion?)

### Anatomical distribution
- Lesions to the carotid arteries especially the common carotid artery and brachiocephalic or subclavian artery were significantly more common in secondary hAVFs than primary hAVFs. 
- Brachiocephalic or subclavian veins and internal jugular were also  significantly more common affected in secondary AVF. The external jugular vein and it's afferents were more commonly affected in primary AVF.


### Treatment
- no sigificant difference between recurrence and adverse event, or residual symptoms


## Discussion
Publication bias 
Multicenter

- Endovascular treatment can be repeated.
- direct puncture not advised, high rate of recurrence.

Report of favorable outcomes, so low adverse events reported. 
Possibly lower report of regular cases (since already published)

Mortality in article Robbs et al. With arterial reconstruction as treatment method revealed a mortality of 2% within then first week, unrelated to the procedure and among the patients treated more than one week after injury 12% died from postoperative complications. Recurrence was 2% [@Robbs:1994je]. 

### Primary AVF
### Secondary AVF
The most common affected vessels in traumatic AVF are the common carotid artery and internal jugular vein considering traumatic AVF over the whole body [@Robbs:1994je].

## Acknowledgements
- martijn heijman

## Disclosure
The authors report no conflict of interest concerning the mate- rials or methods used in this study or the findings specified in this paper.
Author contributions to the study and manuscript preparation include the following. Conception and design: Du, Gross. Acqui- sition of data: Huang, Gross. Analysis and interpretation of data: all authors. Drafting the article: Huang, Gross. Critically revising the article: all authors. Reviewed submitted version of manuscript: all authors. Approved the final version of the manuscript on behalf of all authors: Du. Administrative/technical/material support: Du. Study supervision: Du.

#### References


[^1]: Visual impairment: blurry vision, decreased vision, diplopia, visual field defect (BLV, DECV, DIP, VFD)
[^2]: Intracranial symptoms: Transient ischemic attack, seizures, SAH, intracranial steal, intracranial embolic stroke, intracranial bleeding, ataxia, acute loss of consciousness (TIA, SEIZ, SAH, INST, INES, INTB, ATAX, ALC, SEIZ, TIA, VOM) 
[^3]: Spinal cord compression: incontinence, myelopathy, neurologic deficit, (upper extremity weekness) quadriparesis, Radiculopathy, spinal cord compression, upper limb edema, upper limb ischemia, upper limb muscle weakness, (INCO, MYE, NEDE, QUA, RADI, SPCC, ULE, UAI, UAM)
[^4]: extracranial hemorrhage: hemorrhage, ecchymosis, bleeding, gum bleeding, bleeding after tooth extraction,  (HEMO, ECCY, GUMB, BLEED, BLEEDT)
[^5]: ocular symptoms: chemotic, epiphora, high intra-ocular pressure, orbital swelling, proptosis (CHEM, EPIP, HIP, ORBS, PROP)  